### PR TITLE
Added midi channel to eventJson

### PR DESCRIPTION
**Pull request by wwlib**
Allows multiple tracks to send notes to the same channel/synth.

### CODE REVIEW

**Comment by wwlib** [comment]
Note: On the the midi files that I tested, the vlv byteCount was always 1 for these meta text events. Allowing it to be more than 1 caused overruns when determining the end of the string data.

**Comment by wwlib** [comment]
Also: Added an optional startTime parameter to the play() method. This allows an absolute start time to be specified which is important when syncing multiple players on multiple devices simultaneously.

**Comment by grimmdude** [comment]
Actually, what do you think about adding a `setStartTime()` method instead of using an argument in `play()`?  I'm not exactly sure I understand the need for the start time setting, but it might be useful to be able to set that separately from the `play()` method.

-Garrett

**Comment by wwlib** [comment]
A setStartTime() method or playWithStartTime() would work. I am running your player (very nice, btw) on number of devices and synchronizing the playback by sending a socket message to all the devices with an absolute start time (a second or two in the future). As long as the device clocks are sync'd it works, and they all use the same start time reference to play back events. Otherwise they can all establish slightly different start times.

**Comment by grimmdude** [comment]
Hi @wwlib ,

Gotcha.  I'd prefer if we went with the `setStartTime()` method versus adding another layer within the `play()` method.  I feel like being able to set the start time outside of the `play()` method could be useful in some cases.  Sorry if I'm being too be pedantic.

-Garrett

**Comment by wwlib** [comment]
No problem. I added setStartTime() and removed playWithStartTime().

Andrew

**Pull request merged**
